network:
  version: 2
  wifis:
    wlan0:
      renderer: NetworkManager
      optional: true
      dhcp4: true
      addresses:
        - 192.168.42.1/24
      access-points:
        "hotspot-user":
          mode: ap
          password:
          hidden:
